# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - await_only_futures
    - prefer_single_quotes

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    constant_identifier_names: ignore
    included_file_warning: ignore
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore
    implicit_dynamic_type: ignore
    implicit_dynamic_map_literal: ignore
    always_put_control_body_on_new_line: ignore
  exclude:
    - "vendors/**"
    - "resources/**"
    - "**/*.iconfig.dart"
    - "**/di.iconfig.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "lib/common/router/router.gr.dart"
    - "component_templates/**"
    - "packages/**"
